apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: swoutch/echo-flask
        name: hello-app
        imagePullPolicy: Always
        env:
        - name: MSG
          value: '{"name": "Rémy", "passion": "Capoeira"}'
