apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    ma-cle: ma-valeur
spec:
  containers:
  - image: swoutch/echo-flask
    name: echo-container
    imagePullPolicy: Always
    env:
    - name: MSG
      value: "Pod exposé\n"
--- # We can define several resources inside the same file
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    autre-cle: autre-valeur
spec:
  containers:
  - image: swoutch/echo-flask
    name: echo-container
    imagePullPolicy: Always
    env:
    - name: MSG
      value: "Pod non exposé\n"
